version: '3'
services:
  php:
    build:
      context: .
      dockerfile: DockerfilePHP
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: DockerfileNging
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    networks:
      - app-network

networks:
  app-network: